<?php

namespace common\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "profile_info".
 *
 * @property int $userid
 * @property int $phone_number
 * @property string $full_name
 * @property string $about
 * @property string|null $image
 * @property int $height
 * @property int $age
 * @property int $distance_day
 * @property int $distance_week
 * @property int $distance_all
 * @property int $desired_distance
 * @property int $recommended_distance
 *
 * @property User $user
 */
class ProfileInfo extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'profile_info';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phone_number', 'full_name', 'about', 'height', 'age', 'desired_distance'], 'required'],
            [['phone_number', 'height', 'age', 'distance_day', 'distance_week', 'distance_all', 'desired_distance', 'recommended_distance'], 'integer'],
            [['full_name', 'about', 'image'], 'string', 'max' => 255],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['userid' => 'id']],
        ];
    }
    public function  __get($name)
    {
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'userid' => 'Userid',
            'phone_number' => 'Phone Number',
            'full_name' => 'Full Name',
            'about' => 'About',
            'image' => 'Image',
            'height' => 'Height',
            'age' => 'Age',
            'distance_day' => 'Distance Day',
            'distance_week' => 'Distance Week',
            'distance_all' => 'Distance All',
            'desired_distance' => 'Desired Distance',
            'recommended_distance' => 'Recommended Distance',
        ];
    }
    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'userid']);
    }
}
