version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    image: php:8-fpm
    volumes:
      - ./app:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"